ALTER TABLE companies
ADD COLUMN IF NOT EXISTS address VARCHAR(512);

ALTER TABLE companies
ADD COLUMN IF NOT EXISTS website VARCHAR(512);

ALTER TABLE companies
ADD COLUMN IF NOT EXISTS phone VARCHAR(64);

ALTER TABLE companies
ADD COLUMN IF NOT EXISTS email VARCHAR(256);
