version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: osintdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"

  api:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:password@postgres:5432/osintdb
      JWT_SECRET: supersecretchangeme
    ports:
      - "8000:8000"
    volumes:
      - ./core-api:/app/core-api

volumes:
  postgres_data:
